### ISSUE TITLE
Observers no longer loaded in 0.1.4

### ISSUE THREAD

**Issue by krisleech** [rails/rails-observers#60]
I suspect this might well be related to existing issues, but they date back a few years, so I thought I'd open a new issue. After upgrading to 0.1.4 (from 0.1.2) the observers are no longer loaded. 

I it looks like there was no 0.1.3 or it was yanked.

The work around is to lock to "0.1.2":

```
gem "rails-observers", "0.1.2"
```

This is Rails 4.2

**Comment by swobspace** [comment]
Same problem here with rails 4.2.9. The observers works some times, some times not in both development and test. I switched back to rails-observer 0.1.2. All problems gone.

**Comment by intrip** [comment]
Experiencing the same problem here, Rails 4.2.9 observers 0.1.4. Switching back to 0.1.2 solved the problem

**Comment by kaspth** [comment]
I've just pushed 0.1.5 with #65 that should fix this. Let me know!

**Comment by IzikAJ** [comment]
on rails 4.2.8 & rails-observers 0.1.5 in production environment issue still present (all ok in development)
easiest solution is to add observers manually:
`
    config.after_initialize do
      ActiveRecord::Base.add_observer CacheObserver.instance
    end
`
